### ISSUE TITLE
Add more Hackerrank problems with solutions | C++

### ISSUE THREAD

**Issue by GunjanMA** [sunnysetia93/competitive-coding-problems#15]
I want to contribute to this issue... kindly assign it

**Comment by sunnysetia93** [comment]
Sure.

**Comment by Mayank662** [comment]
Hi @sunnysetia93  I would like to add some Hackerrank problems with solution in C++.
Please assign me this issue.

**Comment by sunnysetia93** [comment]
Assigned @Mayank662

**Comment by ivinaypathak** [comment]
I would like to work on solution to the problem [https://www.hackerrank.com/challenges/journey-to-the-moon/problem?h_r=profile](url) .

**Comment by sunnysetia93** [comment]
> Hey @sunnysetia93 .I would like to work on a solution to the problem Journey To The Moon (Hackerrank).

Sure @ivinaypathak 
Please go ahead. Do go through CONTRIBUTIONS.md first.
