### ISSUE TITLE
Add Unit Test cases for any existing solution

### ISSUE THREAD

**Issue by sunnysetia93** [sunnysetia93/competitive-coding-problems#2]
Hey

Having unit test cases for a programming solution is a great plus, as It assures developer that the code is giving desirable results and also helps in improving the solution when one starts finding edge cases.

This issue is a way to promote Test-driven development. Since this has not been followed majorly in this repo, the focus is to do create test cases and improve the existing solutions.

PRs are welcome. 

Thanks

**Comment by Andrsrz** [comment]
Hi there, I can help with that. Can you assign me?.

**Comment by sunnysetia93** [comment]
Sure.
Please create a sub-folder named "tests" inside the main folder (eg: _"Leetcode_May_Challenge_Covid19"_ folder) 
and keep adding test cases for related files keeping the conventions as **`filename.test.js`**

**Comment by sunnysetia93** [comment]
@Andrsrz any update here?
can you share a timeline for this task if you are working on this?

**Comment by Andrsrz** [comment]
@sunnysetia93 Hi. Yes, I just forked the repo. I'm going to start working on it today. By late today or tomorrow morning I'll open a PR according to this issue.

**Comment by sunnysetia93** [comment]
Alright. Thanks @Andrsrz 👍
