### ISSUE TITLE
Leetcode Problem | Burst Balloons | C++

### ISSUE THREAD

**Issue by chiyapathak** [sunnysetia93/competitive-coding-problems#37]
### Burst Balloons
I woluld like to add burst balloons leetcode problem.

**Comment by sunnysetia93** [comment]
Sure 
Please go ahead

Do read the **contributions.md** and refer other solutions for code structure. 

Thanks

**Comment by chiyapathak** [comment]
Please add the appropriate(Hacktoberfest) label.
