### ISSUE TITLE
Add Leetcode problems and their solutions | C++

### ISSUE THREAD

**Issue by GunjanMA** [sunnysetia93/competitive-coding-problems#6]
I would like to add solutions to some leetcode problems in C++. Kindly assign this issue to me.

**Comment by sunnysetia93** [comment]
Sure. I have assigned the issue to you. 
Please go ahead. 

P.S.: **Do read the contribution.md**

**Comment by GunjanMA** [comment]
Thank you so much !!! you helped me in my first ever contribution to open source... would be contributing even more to this repo.
Btw, contributions to this are being accepted in hacktoberfest right ???

**Comment by sunnysetia93** [comment]
Most Welcome @GunjanMA 
Keep Contributing.

Yes, accepted in hacktoberfest.

**Comment by sunnysetia93** [comment]
if you'll be contributing, I'll keep this issue open? @GunjanMA

**Comment by GunjanMA** [comment]
> if you'll be contributing, I'll keep this issue open? @GunjanMA

Yes... I'll be adding more... Kindly don't close it

**Comment by sunnysetia93** [comment]
> > if you'll be contributing, I'll keep this issue open? @GunjanMA
> 
> Yes... I'll be adding more... Kindly don't close it

Sure. 👍

**Comment by bhavidhingra** [comment]
Please assign this issue to me as well.

**Comment by sunnysetia93** [comment]
> Please assign this issue to me as well.

Sure. Assigned. 👍

**Comment by sunnysetia93** [comment]
@all-contributors please add @bhavidhingra Leet code C++ Solutions

**Comment by sunnysetia93** [comment]
@all-contributors please add @bhavidhingra Leet code C++ Solutions
